name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.19.3'
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Lint 🧪
        run: yarn lint
  test_on_windows:
    name: Test on Windows with Node 14
    needs:
      - lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.19.3'
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Run tests 🧪
        run: yarn test
  test_on_macos:
    name: Test on MacOS with Node 14
    needs:
      - lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.19.3'
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Run tests 🧪
        run: yarn test
  test_on_linux:
    name: Test on Ubuntu with Node ${{ matrix.node }}
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14.19.3', '16.15.0']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Run tests 🧪
        run: yarn test
  coverage:
    name: Coverage
    needs:
      - test_on_windows
      - test_on_macos
      - test_on_linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14.19.3'
        cache: yarn
    - name: Install
      run: yarn --frozen-lockfile
    - name: Run coverage 🧪
      run: yarn coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
